'use strict';

/**
 * VENDORED from @rutba/mail-dns (consumer/packages/mail-dns/src/checks.js).
 *
 * Rutba MTA is a separately clonable AGPL product and cannot take a
 * file: dependency on the consumer repo. The shared checks live in
 * consumer/packages/mail-dns; this file is output, not source.
 *
 * Do not edit this file. Edit the source and re-run:
 *   node consumer/devkit/scripts/js/sync-vendored.js
 * The --check form of that command fails the build when this copy drifts.
 */

// ==== BEGIN VENDORED COPY - DO NOT EDIT BELOW THIS LINE ====
'use strict';

/**
 * DNS record checks for mail domains - one definition of what "verified"
 * means, for every part of the estate that asks the question.
 *
 * Two products ask it, for two different reasons, and both are served here:
 *
 *   HOSTING (comm.mail / the ERP mail-domain path) - "will mail for this
 *     domain arrive at our mailboxes, and will what we send be trusted?"
 *     Blocking: MX + SPF + DKIM. We hold the signing key, so DKIM is checked
 *     by KEY MATCH: a stale key from a previous provider passes a presence
 *     check and still fails every signature.
 *
 *   SENDING (Rutba MTA's dns-gate) - "may this sender relay through us?"
 *     Blocking: SPF + DKIM, no MX (a relay customer's mail need not arrive
 *     here). The MTA relays through the sender's own SMTP server and never
 *     holds the signing key, so DKIM is PRESENCE-only: it can prove the
 *     sender published *a* key at the selector they named, no more.
 *
 * The difference between them is which options the caller passes, not which
 * implementation runs. That is the whole point of this file: the two used to
 * be separate copies and they forked - the ERP's grew key-match, the MTA's
 * did not, and neither knew.
 *
 * Contract, uniform across every check:
 *   - the resolver is injectable, so tests pin answers instead of the internet;
 *   - each check returns { ok, observed, missing? } and NEVER throws on
 *     NXDOMAIN or an empty answer - "the record is not there" is the finding,
 *     not an error. Only a malformed input throws;
 *   - DMARC is checked but ADVISORY: absence never blocks. It is reported so
 *     a console can nag, because a domain without DMARC deliverability-
 *     degrades slowly rather than failing loudly.
 */

const { promises: realDns } = require('node:dns');

/** Mailcow signs with the `dkim` selector; callers that know better pass one. */
const DEFAULT_DKIM_SELECTOR = 'dkim';

const norm = (d) => String(d || '').trim().toLowerCase().replace(/\.$/, '');

/** TXT answers arrive as chunk arrays; a record is the chunks joined. */
async function txtRecords(resolver, name) {
  try {
    const rows = await resolver.resolveTxt(name);
    return rows.map((chunks) => chunks.join(''));
  } catch (e) {
    if (e && (e.code === 'ENOTFOUND' || e.code === 'ENODATA')) return [];
    throw e;
  }
}

/**
 * MX: at least one MX record, and - when an expected host is known - one of
 * them pointing at it. A domain MXing elsewhere is not hosted by us, and
 * provisioning a mailbox we will never receive mail for helps nobody.
 *
 * Not asked of sending domains: a relay customer's inbound is their business.
 */
async function checkMx(domain, { expectedHost, resolver = realDns } = {}) {
  const name = norm(domain);
  if (!name) throw new Error('checkMx: domain is required');
  let rows;
  try {
    rows = await resolver.resolveMx(name);
  } catch (e) {
    if (e && (e.code === 'ENOTFOUND' || e.code === 'ENODATA')) rows = [];
    else throw e;
  }
  const observed = (rows || []).map((r) => ({ exchange: norm(r.exchange), priority: r.priority }));
  const wanted = norm(expectedHost);
  const ok = observed.length > 0 && (!wanted || observed.some((r) => r.exchange === wanted));
  return { ok, observed, ...(ok ? {} : { missing: wanted ? `MX -> ${wanted}` : 'MX' }) };
}

/**
 * SPF: exactly one v=spf1 TXT at the apex (more than one is itself a fault -
 * RFC 7208 says receivers treat multiple SPF records as a permerror),
 * containing the expected token (an include: or the mail host) when one is
 * known.
 */
async function checkSpf(domain, { expectedToken, resolver = realDns } = {}) {
  const name = norm(domain);
  if (!name) throw new Error('checkSpf: domain is required');
  const all = await txtRecords(resolver, name);
  const observed = all.filter((t) => /^v=spf1(\s|$)/i.test(t.trim()));
  if (observed.length !== 1) {
    return {
      ok: false,
      observed,
      missing: observed.length === 0
        ? 'SPF (a v=spf1 TXT record)'
        : 'exactly one SPF record (multiple found)',
    };
  }
  const token = String(expectedToken || '').trim().toLowerCase();
  const ok = !token || observed[0].toLowerCase().includes(token);
  return { ok, observed, ...(ok ? {} : { missing: `SPF containing ${token}` }) };
}

/** Strip whitespace and quote seams so two spellings of one key compare equal. */
const normalizeDkimValue = (t) => String(t || '').replace(/["\s]/g, '');

/** The p= payload of a DKIM record, or '' when there is none. */
const dkimKeyOf = (value) => (normalizeDkimValue(value).match(/p=([^;]+)/i) || [])[1] || '';

/**
 * DKIM: a v=DKIM1 TXT with a non-empty p= at {selector}._domainkey.{domain}.
 *
 * `expectedKey` is what separates the two products. Pass it (hosting: fetch
 * the public key from the signing server) and the published key must MATCH.
 * Omit it (sending: we do not hold the key) and presence is all that can
 * honestly be asserted. `expectedKey` may be a whole TXT record or a bare
 * key - only the p= payload is compared either way.
 */
async function checkDkim(domain, { selector, expectedKey, resolver = realDns } = {}) {
  const name = norm(domain);
  if (!name) throw new Error('checkDkim: domain is required');
  const sel = String(selector || DEFAULT_DKIM_SELECTOR).trim();
  const host = `${sel}._domainkey.${name}`;
  const observed = await txtRecords(resolver, host);

  // Prefer a record that actually carries a key. A zone can hold both a
  // revoked `v=DKIM1; p=` and a live one; picking whichever came first would
  // make the verdict depend on answer order.
  const values = observed.map(normalizeDkimValue);
  const record =
    values.find((t) => /(^|;)p=[^;]+/i.test(t)) ||
    values.find((t) => /(^|;)v=DKIM1(;|$)/i.test(t) || /(^|;)p=/i.test(t));

  if (!record || !/(^|;)p=[^;]+/i.test(record)) {
    // Covers both "nothing published" and "published, but the key is revoked".
    return { ok: false, observed, missing: `DKIM (a TXT record with a key at ${host})` };
  }

  if (expectedKey) {
    const wanted = dkimKeyOf(expectedKey) || normalizeDkimValue(expectedKey);
    const got = dkimKeyOf(record);
    if (wanted && got !== wanted) {
      return { ok: false, observed, missing: `DKIM key at ${host} matching the server's key` };
    }
  }
  return { ok: true, observed };
}

/**
 * PTR / forward-confirmed reverse DNS for every address a mail host answers on.
 *
 * The check that catches the classic provider-default-PTR defect, and the one
 * the estate is currently failing: the A record's PTR is set correctly, the
 * AAAA record's is still the hosting vendor's own hostname, every IPv4
 * hand-test passes, and outbound over IPv6 fails FCrDNS at Google and other
 * large receivers. Half-configured is the worst state - it looks fine.
 *
 * Forward-confirmed means both directions agree: address -> PTR name, and
 * that name -> back to the same address. A PTR alone is forgeable by whoever
 * controls the reverse zone, so receivers that care check both.
 *
 * Per-family verdicts are reported separately because the remedy differs:
 * a failing IPv4 PTR must be fixed, while a failing IPv6 one can be fixed OR
 * routed around by disabling IPv6 egress (mailcow ENABLE_IPV6=false) until it
 * is. Callers need to be able to tell those two apart.
 */
async function checkPtr(host, { expectedHost, resolver = realDns } = {}) {
  const name = norm(host);
  if (!name) throw new Error('checkPtr: a host is required');
  const wanted = norm(expectedHost) || name;

  const addressesOf = async (method) => {
    try {
      return (await resolver[method](name)) || [];
    } catch (e) {
      // No AAAA is not a fault - a v4-only host is a legitimate posture.
      if (e && (e.code === 'ENOTFOUND' || e.code === 'ENODATA')) return [];
      throw e;
    }
  };
  const [v4, v6] = await Promise.all([addressesOf('resolve4'), addressesOf('resolve6')]);

  const inspect = async (address, family) => {
    let names = [];
    try {
      names = (await resolver.reverse(address)) || [];
    } catch (e) {
      if (!(e && (e.code === 'ENOTFOUND' || e.code === 'ENODATA'))) throw e;
    }
    const ptr = names.map(norm);
    if (ptr.length === 0) {
      return { address, family, ptr, ok: false, missing: `PTR for ${address} (large receivers reject on this alone)` };
    }
    if (!ptr.includes(wanted)) {
      return {
        address, family, ptr, ok: false,
        missing: `PTR for ${address} -> ${ptr.join(', ')}, expected ${wanted}`,
      };
    }
    // The forward half. `wanted` is normally the host we just resolved, so the
    // answers are already in hand; only look again when it is some other name.
    let forward = family === 'ipv6' ? v6 : v4;
    if (wanted !== name) {
      try {
        forward = (await resolver[family === 'ipv6' ? 'resolve6' : 'resolve4'](wanted)) || [];
      } catch (e) {
        if (e && (e.code === 'ENOTFOUND' || e.code === 'ENODATA')) forward = [];
        else throw e;
      }
    }
    if (!forward.includes(address)) {
      return {
        address, family, ptr, ok: false,
        missing: `${wanted} does not resolve back to ${address} (reverse set, forward does not confirm)`,
      };
    }
    return { address, family, ptr, ok: true };
  };

  const observed = await Promise.all([
    ...v4.map((a) => inspect(a, 'ipv4')),
    ...v6.map((a) => inspect(a, 'ipv6')),
  ]);

  const byFamily = (f) => observed.filter((r) => r.family === f);
  const familyOk = (f) => {
    const rows = byFamily(f);
    return rows.length > 0 && rows.every((r) => r.ok);
  };

  if (observed.length === 0) {
    return { ok: false, observed, ipv4Ok: false, ipv6Ok: null, missing: [`no A or AAAA record for ${name}`] };
  }

  return {
    ok: observed.every((r) => r.ok),
    observed,
    ipv4Ok: familyOk('ipv4'),
    // null, not false: a host with no AAAA is not failing IPv6, it is not on it.
    ipv6Ok: byFamily('ipv6').length ? familyOk('ipv6') : null,
    missing: observed.filter((r) => !r.ok).map((r) => r.missing),
  };
}

/** DMARC: advisory. Reported, never blocking. */
async function checkDmarc(domain, { resolver = realDns } = {}) {
  const name = norm(domain);
  if (!name) throw new Error('checkDmarc: domain is required');
  const all = await txtRecords(resolver, `_dmarc.${name}`);
  const observed = all.filter((t) => /^v=DMARC1(\s|;|$)/i.test(t.trim()));
  return {
    ok: observed.length > 0,
    observed,
    advisory: true,
    ...(observed.length ? {} : { missing: `DMARC TXT at _dmarc.${name}` }),
  };
}

/**
 * HOSTING verdict for one domain against its expected records.
 * Blocking = MX + SPF + DKIM; DMARC rides along as advisory.
 */
async function verifyDomain(domain, expected = {}, { resolver = realDns } = {}) {
  const [mx, spf, dkim, dmarc] = await Promise.all([
    checkMx(domain, { expectedHost: expected?.mx?.host, resolver }),
    checkSpf(domain, { expectedToken: expected?.spf?.token, resolver }),
    checkDkim(domain, { selector: expected?.dkim?.selector, expectedKey: expected?.dkim?.txt, resolver }),
    checkDmarc(domain, { resolver }),
  ]);

  const missing = [mx, spf, dkim].filter((r) => !r.ok).map((r) => r.missing);
  return {
    ok: missing.length === 0,
    missing,
    observed: { mx: mx.observed, spf: spf.observed, dkim: dkim.observed, dmarc: dmarc.observed },
    mxOk: mx.ok,
    spfOk: spf.ok,
    dkimOk: dkim.ok,
    dmarcOk: dmarc.ok,
  };
}

/**
 * SENDING verdict for one relay customer's domain.
 * Blocking = SPF + DKIM presence at the named selector; no MX, no key match -
 * see the header. DMARC is reported alongside.
 */
async function verifySendingDomain(domain, { selector, resolver = realDns } = {}) {
  const [spf, dkim, dmarc] = await Promise.all([
    checkSpf(domain, { resolver }),
    checkDkim(domain, { selector, resolver }),
    checkDmarc(domain, { resolver }),
  ]);
  const missing = [spf, dkim].filter((r) => !r.ok).map((r) => r.missing);
  return {
    ok: missing.length === 0,
    missing,
    observed: { spf: spf.observed, dkim: dkim.observed, dmarc: dmarc.observed },
    spfOk: spf.ok,
    dkimOk: dkim.ok,
    dmarcOk: dmarc.ok,
  };
}

/**
 * Ownership: a TXT record at `<prefix>.<domain>` carrying an exact token.
 *
 * Not mail-specific, and exported because the same question - "does whoever
 * asked for this actually control the zone" - is asked of storefront
 * hostnames too (see api/org-domain). The definition of a satisfied TXT
 * challenge lives here with the rest of "what verified means", rather than
 * being written twice and drifting.
 *
 * Same contract as the checks above: never throws on a missing record,
 * because "not published yet" is the normal state while DNS propagates.
 */
async function checkOwnershipTxt(domain, { expectedToken, prefix = '_rutba-verify', resolver = realDns } = {}) {
  const d = norm(domain);
  if (!d) throw new Error('a domain is required');
  if (!expectedToken) throw new Error('an expected token is required');

  const name = `${prefix}.${d}`;
  let observed = [];
  try {
    observed = await txtRecords(resolver, name);
  } catch (e) {
    return { ok: false, name, observed: [], error: e.message };
  }
  const trimmed = observed.map((v) => String(v).trim());
  return { ok: trimmed.includes(String(expectedToken)), name, observed: trimmed };
}

module.exports = {
  DEFAULT_DKIM_SELECTOR,
  checkMx, checkSpf, checkDkim, checkDmarc, checkPtr,
  verifyDomain, verifySendingDomain,
  // Exported for non-mail callers; see checkOwnershipTxt's note.
  checkOwnershipTxt, txtRecords,
};
